### ISSUE TITLE
Code publication

### ISSUE THREAD

**Issue by AufarZakiev** [ANRGUSC/ROMANO#1]
Hello, I study multi-robot cooperation and looking for inter-robot communication protocols.
I am very interested in your paper about ROMANO protocol and wanted to see source codes of your project. 
It is a long time since publication, is the source code available for publication?

**Comment by iampradiptaghosh** [comment]
Sorry. The codes are not public yet as the paper is still not published. We do have a arxiv version. but that does not count as publication. We are in process of publishing it.
